# Generated by Django 4.0.5 on 2022-06-24 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='code_postal',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un code postal valide', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')]),
        ),
    ]
